language: cpp

compiler:
  - gcc
  - clang

before_install:
  - source ci/obs_common.sh
  - source ci/obs_before_install.sh
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq

before_script:
  - sudo apt-get install -qq libstdc++-4.8-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get update -qq
  - sudo apt-get install devscripts equivs
  - sudo mk-build-deps -i

script:
  - ./autogen.sh
  - ./configure --prefix=$HOME
  - make clean
  - make
  - make install
  - PYTHONPATH=$HOME/lib/python2.7/site-packages make check
  - source ci/obs_prepare.sh

after_success:
  - source ci/obs_commit.sh

env:
  global:
    - secure: "R7uaqRSdJS8UW0nFjQSpa2NIVcd/0L50S6/opYRgib0pYop59AME5/0Z+tFyexezqLO5u8nBYyjXic+jcsABHudboSe61hi8d5US5eU+fq7zecfXUV5w9GaDNO6Ue0HydsAfGo6HTSRblrj+NyO9T3LeBr2hLTilQi3fziGLlcE="
    - OBS_HOME=security
    - OBS_PROJECT=Zorp
    - OBS_SUBPROJECT=6.0
    - OBS_PACKAGE=zorp
